package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

    private Integer idAddress;
    private User user;
    private String name;
    private String contactNo;
    private String line1;
    private String line2;
    private String city;
    private Integer zipCode;
    private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public Address() {
    }

    public Address(User user) {
        this.user = user;
    }

    public Address(User user, String name, String contactNo, String line1, String line2, String city, Integer zipCode, Set<Invoice> invoices) {
        this.user = user;
        this.name = name;
        this.contactNo = contactNo;
        this.line1 = line1;
        this.line2 = line2;
        this.city = city;
        this.zipCode = zipCode;
        this.invoices = invoices;
    }

    public Integer getIdAddress() {
        return this.idAddress;
    }

    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    public String getLine1() {
        return this.line1;
    }

    public void setLine1(String line1) {
        this.line1 = line1;
    }

    public String getLine2() {
        return this.line2;
    }

    public void setLine2(String line2) {
        this.line2 = line2;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Integer getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }

    public Set<Invoice> getInvoices() {
        return this.invoices;
    }

    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }

    @Override
    public String toString() {
        return name + "\n" + line1 + "\n" + line2 + "\n" + city + "\n" + zipCode;
    }

}
