package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private Integer idGrn;
     private Supplier supplier;
     private Date date;
     private Date time;
     private Integer itemCount;
     private Double nettotal;
     private Set<Grnitem> grnitems = new HashSet<Grnitem>(0);
     private Set<Stock> stocks = new HashSet<Stock>(0);

    public Grn() {
    }

	
    public Grn(Supplier supplier) {
        this.supplier = supplier;
    }
    public Grn(Supplier supplier, Date date, Date time, Integer itemCount, Double nettotal, Set<Grnitem> grnitems, Set<Stock> stocks) {
       this.supplier = supplier;
       this.date = date;
       this.time = time;
       this.itemCount = itemCount;
       this.nettotal = nettotal;
       this.grnitems = grnitems;
       this.stocks = stocks;
    }
   
    public Integer getIdGrn() {
        return this.idGrn;
    }
    
    public void setIdGrn(Integer idGrn) {
        this.idGrn = idGrn;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Integer getItemCount() {
        return this.itemCount;
    }
    
    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }
    public Double getNettotal() {
        return this.nettotal;
    }
    
    public void setNettotal(Double nettotal) {
        this.nettotal = nettotal;
    }
    public Set<Grnitem> getGrnitems() {
        return this.grnitems;
    }
    
    public void setGrnitems(Set<Grnitem> grnitems) {
        this.grnitems = grnitems;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }




}


