package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0



/**
 * Grnitem generated by hbm2java
 */
public class Grnitem  implements java.io.Serializable {


     private Integer idGrnitem;
     private Grn grn;
     private Product product;
     private User user;
     private Double price;
     private Integer qty;

    public Grnitem() {
    }

	
    public Grnitem(Grn grn, Product product, User user) {
        this.grn = grn;
        this.product = product;
        this.user = user;
    }
    public Grnitem(Grn grn, Product product, User user, Double price, Integer qty) {
       this.grn = grn;
       this.product = product;
       this.user = user;
       this.price = price;
       this.qty = qty;
    }
   
    public Integer getIdGrnitem() {
        return this.idGrnitem;
    }
    
    public void setIdGrnitem(Integer idGrnitem) {
        this.idGrnitem = idGrnitem;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


