package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0



/**
 * Invoiceitem generated by hbm2java
 */
public class Invoiceitem  implements java.io.Serializable {


     private Integer idInvoiceItem;
     private Invoice invoice;
     private Product product;
     private Stock stock;
     private Double price;
     private Integer qty;

    public Invoiceitem() {
    }

	
    public Invoiceitem(Invoice invoice, Product product, Stock stock) {
        this.invoice = invoice;
        this.product = product;
        this.stock = stock;
    }
    public Invoiceitem(Invoice invoice, Product product, Stock stock, Double price, Integer qty) {
       this.invoice = invoice;
       this.product = product;
       this.stock = stock;
       this.price = price;
       this.qty = qty;
    }
   
    public Integer getIdInvoiceItem() {
        return this.idInvoiceItem;
    }
    
    public void setIdInvoiceItem(Integer idInvoiceItem) {
        this.idInvoiceItem = idInvoiceItem;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


