package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0



/**
 * Invocartsession generated by hbm2java
 */
public class Invocartsession  implements java.io.Serializable {


     private Integer idInvoCartSession;
     private User user;
     private Stock stock;
     private Integer qty;

    public Invocartsession() {
    }

	
    public Invocartsession(User user, Stock stock) {
        this.user = user;
        this.stock = stock;
    }
    public Invocartsession(User user, Stock stock, Integer qty) {
       this.user = user;
       this.stock = stock;
       this.qty = qty;
    }
   
    public Integer getIdInvoCartSession() {
        return this.idInvoCartSession;
    }
    
    public void setIdInvoCartSession(Integer idInvoCartSession) {
        this.idInvoCartSession = idInvoCartSession;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


