package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0



/**
 * Paymentdetails generated by hbm2java
 */
public class Paymentdetails  implements java.io.Serializable {


     private Integer idpaymentDetails;
     private Invoice invoice;
     private User user;
     private String idTransaction;
     private String idPayer;
     private String payerEmail;
     private String processStatus;

    public Paymentdetails() {
    }

	
    public Paymentdetails(Invoice invoice, User user) {
        this.invoice = invoice;
        this.user = user;
    }
    public Paymentdetails(Invoice invoice, User user, String idTransaction, String idPayer, String payerEmail, String processStatus) {
       this.invoice = invoice;
       this.user = user;
       this.idTransaction = idTransaction;
       this.idPayer = idPayer;
       this.payerEmail = payerEmail;
       this.processStatus = processStatus;
    }
   
    public Integer getIdpaymentDetails() {
        return this.idpaymentDetails;
    }
    
    public void setIdpaymentDetails(Integer idpaymentDetails) {
        this.idpaymentDetails = idpaymentDetails;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getIdTransaction() {
        return this.idTransaction;
    }
    
    public void setIdTransaction(String idTransaction) {
        this.idTransaction = idTransaction;
    }
    public String getIdPayer() {
        return this.idPayer;
    }
    
    public void setIdPayer(String idPayer) {
        this.idPayer = idPayer;
    }
    public String getPayerEmail() {
        return this.payerEmail;
    }
    
    public void setPayerEmail(String payerEmail) {
        this.payerEmail = payerEmail;
    }
    public String getProcessStatus() {
        return this.processStatus;
    }
    
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus;
    }




}


