package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idProduct;
     private String name;
     private Integer minumumQty;
     private String description;
     private String volume;
     private String category;
     private Byte gender;
     private Byte status;
     private String imageurl;
     private Set<Grncartsession> grncartsessions = new HashSet<Grncartsession>(0);
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<Invoiceitem> invoiceitems = new HashSet<Invoiceitem>(0);
     private Set<Grnitem> grnitems = new HashSet<Grnitem>(0);

    public Product() {
    }

    public Product(String name, Integer minumumQty, String description, String volume, String category, Byte gender, Byte status, String imageurl, Set<Grncartsession> grncartsessions, Set<Stock> stocks, Set<Invoiceitem> invoiceitems, Set<Grnitem> grnitems) {
       this.name = name;
       this.minumumQty = minumumQty;
       this.description = description;
       this.volume = volume;
       this.category = category;
       this.gender = gender;
       this.status = status;
       this.imageurl = imageurl;
       this.grncartsessions = grncartsessions;
       this.stocks = stocks;
       this.invoiceitems = invoiceitems;
       this.grnitems = grnitems;
    }
   
    public Integer getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getMinumumQty() {
        return this.minumumQty;
    }
    
    public void setMinumumQty(Integer minumumQty) {
        this.minumumQty = minumumQty;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getVolume() {
        return this.volume;
    }
    
    public void setVolume(String volume) {
        this.volume = volume;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Byte getGender() {
        return this.gender;
    }
    
    public void setGender(Byte gender) {
        this.gender = gender;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }
    public Set<Grncartsession> getGrncartsessions() {
        return this.grncartsessions;
    }
    
    public void setGrncartsessions(Set<Grncartsession> grncartsessions) {
        this.grncartsessions = grncartsessions;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }
    public Set<Invoiceitem> getInvoiceitems() {
        return this.invoiceitems;
    }
    
    public void setInvoiceitems(Set<Invoiceitem> invoiceitems) {
        this.invoiceitems = invoiceitems;
    }
    public Set<Grnitem> getGrnitems() {
        return this.grnitems;
    }
    
    public void setGrnitems(Set<Grnitem> grnitems) {
        this.grnitems = grnitems;
    }




}


