package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer idStock;
     private Grn grn;
     private Product product;
     private Integer qty;
     private Double price;
     private Double sellingPrice;
     private Byte status;
     private Set<Invocartsession> invocartsessions = new HashSet<Invocartsession>(0);
     private Set<Invoiceitem> invoiceitems = new HashSet<Invoiceitem>(0);

    public Stock() {
    }

	
    public Stock(Grn grn, Product product) {
        this.grn = grn;
        this.product = product;
    }
    public Stock(Grn grn, Product product, Integer qty, Double price, Double sellingPrice, Byte status, Set<Invocartsession> invocartsessions, Set<Invoiceitem> invoiceitems) {
       this.grn = grn;
       this.product = product;
       this.qty = qty;
       this.price = price;
       this.sellingPrice = sellingPrice;
       this.status = status;
       this.invocartsessions = invocartsessions;
       this.invoiceitems = invoiceitems;
    }
   
    public Integer getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(Integer idStock) {
        this.idStock = idStock;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Set<Invocartsession> getInvocartsessions() {
        return this.invocartsessions;
    }
    
    public void setInvocartsessions(Set<Invocartsession> invocartsessions) {
        this.invocartsessions = invocartsessions;
    }
    public Set<Invoiceitem> getInvoiceitems() {
        return this.invoiceitems;
    }
    
    public void setInvoiceitems(Set<Invoiceitem> invoiceitems) {
        this.invoiceitems = invoiceitems;
    }




}


