package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer idSupplier;
     private String companyName;
     private String businessAddress;
     private String email;
     private String tel;
     private Byte status;
     private Set<Grn> grns = new HashSet<Grn>(0);

    public Supplier() {
    }

    public Supplier(String companyName, String businessAddress, String email, String tel, Byte status, Set<Grn> grns) {
       this.companyName = companyName;
       this.businessAddress = businessAddress;
       this.email = email;
       this.tel = tel;
       this.status = status;
       this.grns = grns;
    }
   
    public Integer getIdSupplier() {
        return this.idSupplier;
    }
    
    public void setIdSupplier(Integer idSupplier) {
        this.idSupplier = idSupplier;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getBusinessAddress() {
        return this.businessAddress;
    }
    
    public void setBusinessAddress(String businessAddress) {
        this.businessAddress = businessAddress;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Set<Grn> getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set<Grn> grns) {
        this.grns = grns;
    }




}


