package pojos;
// Generated Dec 15, 2019 5:19:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String name;
     private String dob;
     private String mobileNumber;
     private String email;
     private String password;
     private String accountType;
     private Byte status;
     private Set<Invocartsession> invocartsessions = new HashSet<Invocartsession>(0);
     private Set<Grnitem> grnitems = new HashSet<Grnitem>(0);
     private Set<Paymentdetails> paymentdetailses = new HashSet<Paymentdetails>(0);
     private Set<Address> addresses = new HashSet<Address>(0);
     private Set<Grncartsession> grncartsessions = new HashSet<Grncartsession>(0);
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public User() {
    }

    public User(String name, String dob, String mobileNumber, String email, String password, String accountType, Byte status, Set<Invocartsession> invocartsessions, Set<Grnitem> grnitems, Set<Paymentdetails> paymentdetailses, Set<Address> addresses, Set<Grncartsession> grncartsessions, Set<Invoice> invoices) {
       this.name = name;
       this.dob = dob;
       this.mobileNumber = mobileNumber;
       this.email = email;
       this.password = password;
       this.accountType = accountType;
       this.status = status;
       this.invocartsessions = invocartsessions;
       this.grnitems = grnitems;
       this.paymentdetailses = paymentdetailses;
       this.addresses = addresses;
       this.grncartsessions = grncartsessions;
       this.invoices = invoices;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Set<Invocartsession> getInvocartsessions() {
        return this.invocartsessions;
    }
    
    public void setInvocartsessions(Set<Invocartsession> invocartsessions) {
        this.invocartsessions = invocartsessions;
    }
    public Set<Grnitem> getGrnitems() {
        return this.grnitems;
    }
    
    public void setGrnitems(Set<Grnitem> grnitems) {
        this.grnitems = grnitems;
    }
    public Set<Paymentdetails> getPaymentdetailses() {
        return this.paymentdetailses;
    }
    
    public void setPaymentdetailses(Set<Paymentdetails> paymentdetailses) {
        this.paymentdetailses = paymentdetailses;
    }
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }
    public Set<Grncartsession> getGrncartsessions() {
        return this.grncartsessions;
    }
    
    public void setGrncartsessions(Set<Grncartsession> grncartsessions) {
        this.grncartsessions = grncartsessions;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


